---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initial_discovery(initial_discovery)
	incremental_analysis(incremental_analysis)
	human_steering_point(human_steering_point)
	partner_matching(partner_matching)
	confidence_assessment(confidence_assessment)
	application_guidance(application_guidance)
	conversation_continuation(conversation_continuation)
	__end__([<p>__end__</p>]):::last
	__start__ --> initial_discovery;
	application_guidance -. &nbsp;END&nbsp; .-> __end__;
	application_guidance -.-> conversation_continuation;
	confidence_assessment -. &nbsp;END&nbsp; .-> __end__;
	confidence_assessment -.-> application_guidance;
	confidence_assessment -.-> conversation_continuation;
	confidence_assessment -.-> partner_matching;
	conversation_continuation -. &nbsp;END&nbsp; .-> __end__;
	conversation_continuation -.-> human_steering_point;
	conversation_continuation -.-> incremental_analysis;
	human_steering_point -. &nbsp;END&nbsp; .-> __end__;
	human_steering_point -.-> incremental_analysis;
	incremental_analysis -. &nbsp;END&nbsp; .-> __end__;
	incremental_analysis -.-> confidence_assessment;
	incremental_analysis -. &nbsp;human_review&nbsp; .-> human_steering_point;
	incremental_analysis -.-> partner_matching;
	initial_discovery -. &nbsp;END&nbsp; .-> __end__;
	initial_discovery -. &nbsp;human_review&nbsp; .-> human_steering_point;
	initial_discovery -. &nbsp;analysis&nbsp; .-> incremental_analysis;
	partner_matching -. &nbsp;END&nbsp; .-> __end__;
	partner_matching -.-> confidence_assessment;
	partner_matching -. &nbsp;human_review&nbsp; .-> human_steering_point;
	human_steering_point -.-> human_steering_point;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
